apiVersion: v1
kind: Service
metadata:
  name: llm-infr-front-service
  namespace: llm-infr
spec:
  selector:
    app: llm-infr-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP